[package]
name = "lisp"
version = "0.1.0"
authors = ["gos-k <mag4.elan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5"
